calendars:

  ekspertnyy-sovet-po-investitsionnoy-politike-i-imuschestvennym-otnosheniyam:
    url: https://www.google.com/calendar/ical/begdg6jdoko70h0md6eb9ieme0%40group.calendar.google.com/public/basic.ics

  ekspertnyy-sovet-po-vnutrenney-politike:
    url: https://www.google.com/calendar/ical/ajghpctik3k02o6a3lb0ubu3g4%40group.calendar.google.com/public/basic.ics

  ekspertnyy-sovet-po-nauchno-obrazovatelnomu-kompleksu-i-innovatsionnoy-politike:
    url: https://www.google.com/calendar/ical/05rcuqhktgerv1g273lqi34p1k%40group.calendar.google.com/public/basic.ics

  ekspertnyy-sovet-po-promyshlennosti-i-tek:
    url: https://www.google.com/calendar/ical/igfriccu71tl013ho2aq05te74%40group.calendar.google.com/public/basic.ics

  ekspertnyy-sovet-po-agropromyshlennoy-politike-i-prirodopolzovaniyu:
    url: https://www.google.com/calendar/ical/mtqrf9f59li6giqlkvl09prdn4%40group.calendar.google.com/public/basic.ics

  ekspertnyy-sovet-po-stroitelstvu-i-infrastrukture:
    url: https://www.google.com/calendar/ical/lk9a111krsoin4ii2sl5eqcf3k%40group.calendar.google.com/public/basic.ics

  ekspertnyy-sovet-po-sotsialnoy-politike:
    url: https://www.google.com/calendar/ical/oaj54j18195v5t37oip8mtii6g%40group.calendar.google.com/public/basic.ics

  ekspertnyy-sovet-po-ekonomike:
    url: https://www.google.com/calendar/ical/k3v4bcc4cp4372ijcuurt8kpsc%40group.calendar.google.com/public/basic.ics

  ekspertnyy-sovet-po-territorialnomu-razvitiyu-i-vzaimodeystviyu-s-organami-mestnogo-samoupravleniya:
    url: https://www.google.com/calendar/ical/4ekkps6nom88lkr5tn8gs08o8o%40group.calendar.google.com/public/basic.ics
